name: checkin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  grouped_list: ^3.1.0
  intl: ^0.15.8
  geolocator: ^5.1.5
  image_picker: ^0.6.7+2
 
dev_dependencies:
  flutter_test:
    sdk: flutter
  http: ^0.12.1
  shared_preferences: any


flutter:

  uses-material-design: true

  assets:
    - assets/syslink.png
    - assets/person.png
    
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Bold.ttf
        - asset: fonts/Prompt-Light.ttf
        - asset: fonts/Prompt-Medium.ttf
        - asset: fonts/Prompt-Regular.ttf