name: syslinkproject
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  curved_navigation_bar: ^0.3.2
  http: ^0.12.1


dev_dependencies:
  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true

  assets:
    - assets/logo.png
    - assets/eye.png
    - assets/lock.png
    - assets/next.png
    - assets/user.png


  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Bold.ttf
        - asset: fonts/Prompt-Light.ttf
        - asset: fonts/Prompt-Medium.ttf
        - asset: fonts/Prompt-Regular.ttf
          