name: checkin
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.3
  grouped_list: ^3.1.0
  intl: ^0.16.1
  geolocator: ^5.1.5
  image_picker: ^0.6.7+2
  http: ^0.12.1
  shared_preferences: any
  dio: ^3.0.9
  logger: ^0.9.1
  buddhist_datetime_dateformat: ^1.0.6
 
dev_dependencies:
  flutter_test:
    sdk: flutter


flutter:

  uses-material-design: true

  assets:
    - assets/syslink.png
    - assets/person.png
    
  fonts:
    - family: Prompt
      fonts:
        - asset: fonts/Prompt-Bold.ttf
        - asset: fonts/Prompt-Light.ttf
        - asset: fonts/Prompt-Medium.ttf
        - asset: fonts/Prompt-Regular.ttf